// Import all your JavaScript files here
import './components/Map.js';
import './components/Modal.js';
import './components/EventGeni.js';
import './components/Calendar.js';
import './components/widgets/Pagewidget.js'
import './components/widgets/Sectionwidget.js'
import './components/widgets/Stickynavbarwidget.js'
import './components/widgets/Popupwidget.js'
import './components/MultipleSectionData.js'
import './components/templates/GridView.js'
import './components/templates/ListView.js'
import './components/templates/listcardstyles/ListCard1.js'  
import './components/templates/listcardstyles/ListCard2.js'  
import './components/templates/listcardstyles/ListCard3.js'  
import './components/templates/CaraouselView.js'  
import './components/templates/popupstyles/PopupController.js'
import './components/templates/popupstyles/portaritstyles/PorPopupview.js'
import './components/templates/popupstyles/landscapestyles/LandPopupview.js'
import './components/templates/popupstyles/portaritstyles/Porpopup1.js'
import './components/templates/popupstyles/portaritstyles/Porpopup2.js'
import './components/templates/popupstyles/portaritstyles/Porpopup3.js'
import './components/templates/popupstyles/landscapestyles/Landpopup1.js'
import './components/templates/popupstyles/landscapestyles/Landpopup2.js'
import './components/templates/popupstyles/landscapestyles/Landpopup3.js'
import './components/templates/HeroBanner.js'
import './components/templates/herobanners/HeroBanner1.js'
import './components/templates/herobanners/HeroBanner2.js'
import './components/templates/herobanners/HeroBanner3.js'
import './components/templates/cardstyles/Card1.js';
import './components/templates/cardstyles/Card2.js';
import './components/templates/cardstyles/Card3.js';
import './components/templates/HeroBannerAndListView.js'
import './components/templates/HeroBannerAndGridView.js'
import './components/templates/CaraouselAndGridView.js'
import './components/templates/CaraouselAndListView.js'
import './components/templates/calendar/MonthCalendar.js'
import './components/templates/calendar/YearCalendar.js'
import './components/templates/calendar/WeekCalendar.js'
import './components/templates/ScrollViewHorizontal.js'
import './components/templates/ScrollViewVertical.js'
// import { handlePopupDisplay } from './components/templates/popupstyles/PopupController.js';

// handlePopupDisplay()
